name: Build and Execute

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build program
      run: |
        MSBuild.exe /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:CharacterSet=Unicode simulationSC_Copy.cpp

    - name: Execute program
      run: |
        simulationSC_Copy.exe Tests\TestCircuit2\testCircuit2.cir Tests\TestCircuit2\stimFileCirc2.stim Tests\TestCircuit2\outputSimulation2.sim Tests\commonoutput.sim
