name: C++ Build and Run (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Program
      run: |
        msbuild /property:Configuration=Release /property:Platform="Win32" simulationSC_Copy.cpp

    - name: Run Program
      run: |
        simulationSC_Copy.exe ${{ env.CIRCUIT_FILE_PATH }} ${{ env.STIMULI_FILE_PATH }} ${{ env.OUTPUT_FILE_PATH }} ${{ env.COMMON_OUTPUT_PATH }}

env:
  CIRCUIT_FILE_PATH: 'Tests\TestCircuit2\testCircuit2.cir'
  STIMULI_FILE_PATH: 'Tests\TestCircuit2\stimFileCirc2.stim'
  OUTPUT_FILE_PATH: 'Tests\TestCircuit2\outputSimulation2.sim'
  COMMON_OUTPUT_PATH: 'Tests\commonoutput.sim'
