name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # Install MSBuild
    - name: Install MSBuild
      run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    # Build the project using MSBuild
    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release

    # Run tests if applicable (replace with your test command)
    - name: Run Tests
      run: echo "No tests configured"

    # Check for errors and exit with non-zero code if any
    - name: Check for Errors
      run: exit 0 # Replace with actual error checking logic if needed
