name: Circuit Simulation Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Build and test
      run: |
        g++ -std=c++11 -o simulationMain simulationMain.cpp
        ./simulationMain "Tests/libFile.lib" "E:\ENG Mohamed\digital desgin repo\Digital_Design_Project_1\Tests\TestCircuit1\testCircuit1.cir" "E:\ENG Mohamed\digital desgin repo\Digital_Design_Project_1\Tests\TestCircuit1\stimFileCirc1.stim" "E:\ENG Mohamed\digital desgin repo\Digital_Design_Project_1\Tests\TestCircuit1\outputSimulation1.sim" "E:\ENG Mohamed\digital desgin repo\Digital_Design_Project_1\Tests\commonoutput.sim"
